# Site settings
url: https://drawcall.dev
title: drawcall.dev
description: Delicious graphics programming with a dash of gamedev on the side.

# Build settings
plugins:
  - jekyll-feed
  - jekyll-seo-tag
sass:
  style: compressed

# Theme settings
remote_theme: riggraz/no-style-please
theme_config:
  appearance: "undefined"
  back_home_text: "../"
  date_format: "%Y-%m-%d"
  show_description: true
